baseURL = 'https://ezrantn.github.io'
languageCode = 'en-us'
title = 'Ezra Natanael'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Personal Blog"

# Appearance settings
theme = 'dark'
colorPalette = 'catpuccin'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = '¡Hola!'
homeIntroContent = """
I'm a Software Engineer based in Indonesia, with a strong interest in distributed systems, databases, cloud computing, and machine learning. Currently, I'm pursuing a Bachelor's degree in Computer Science at Soegijapranata Catholic University. My primary programming language is Go, but I'm also proficient in several others. 

I enjoy building open-source software and have authored articles on topics related to my field—you should check them out. Outside of coding, I enjoy hitting the gym and playing basketball with friends.

Don't hesitate to reach out for questions, collaborations, or just a chat. I'd be happy to connect:

✉️ ezrantn.dev@gmail.com
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ezrantn"

[[params.social]]
name = "medium"
url = "https://medium.com/@ezrantn"

[[params.social]]
name = "github"
url = "https://github.com/ezrantn"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'catppuccin-frappe'

# Giscus comments
[params.giscus]
enable = false
repo = "ezrantn/ezrantn.github.io"
repoid = "849173383"
category = "General"
categoryid = "DIC_kwDOLtSsz84CfLm4"
mapping = "pathname"
theme = "preferred_color_scheme"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false